Random park button on home & search page
tun24709/CIS3296-Lam-Zhang-McBride-04 pull request #5
Opened 2024-10-29 17:48 UTC by tjtemple

Feature 2: Random Park Button
- Button makes an API call for all parks and picks a random one from that list to redirect the user to
- Admittedly, the function used for both buttons is the same in both files and could potentially be reused, but there does not seem to be a place in the file structure for common js functions between components

2024-10-29 18:47 UTC, jonathan-d-zhang requested changes

2024-10-29 18:47 UTC, jonathan-d-zhang commented on exploring-national-parks/src/HomePage/Components/Buttons.jsx
> +    async function randPark() {
Can't we define this once and use it in both spots?

2024-10-29 18:47 UTC, jonathan-d-zhang commented on exploring-national-parks/src/HomePage/Components/Buttons.jsx
> +        const response = await fetch(url);
We already fetch these elsewhere like on the homepage; we can just reuse the data we already have. Use the other PR as an example.

2024-10-30 01:23 UTC, tjtemple commented
Figured that out, imports with React were confusing me last night but it seems like it's good now. And about reusing the data we already have: it's nested in a React UseEffect function so trying to reuse that just bombs the program and doesn't work if I move it out. I made the button change to "Loading..." while the extra API call is made so the user has feedback that they actually pressed the button while it loads for a sec, I don't think it's a massive deal

2024-10-30 03:21 UTC, merged